baseURL = 'https://hirawat.in/'
languageCode = 'en-us'
title = 'vishal hirawat'
theme = "hugo-ink"
paginate = 5

relativeURLs = true
copyright = "© Vishal Hirawat"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# google analytics
googleAnalytics = "G-P3SXMJZ3GX"

[params]
	subtitle = "trailblazer / trader / tinkerer"

	# Optional 64x64 avatar image.
	avatar = "saitama-64x64.webp"

	# Google Fonts
	googleFonts = "Playfair+Display:700"
	
	featherIconsCDN = true
	mermaid = false

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Navigation Menu
[[menu.main]]
name = "posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "present"
url = "/present"
weight = 1

[[menu.main]]
name = "projects"
url = "/projects"
weight = 3

[[params.social]]
name = "github"
icon = "github"
url = "https://github.com/hirawatt"

[[params.social]]
name = "telegram"
icon = "send"
url = "https://t.me/hirawat"

[[params.social]]
name = "mail"
icon = "mail"
url = "mailto:vishal@hirawat.in"

[[params.social]]
name = "twitter"
icon = "twitter"
url = "https://twitter.com/hirawattt"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
tag = "tags"

[sitemap]
changefreq = 'monthly'
filename = 'sitemap.xml'
priority = 0.5