baseURL = 'https://hirawat.in/'
languageCode = 'en-us'
title = 'vishal hirawat'
theme = "hugo-ink"
paginate = 5

relativeURLs = true
copyright = "© Copyright"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	subtitle = ""

	# Optional 64x64 avatar image.
	avatar = ""

	# Google Fonts
	googleFonts = "Playfair+Display:700"
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "home"
url = "/"
weight = 1

[[menu.main]]
name = "posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "now"
url = "/now"
weight = 4

[[menu.main]]
name = "projects"
url = "/projects"
weight = 3

[[params.social]]
name = "github"
icon = "github"
url = "https://github.com/hirawatt"

[[params.social]]
name = "telegram"
icon = "send"
url = "https://t.me/hirawat"

[[params.social]]
name = "mail"
icon = "mail"
url = "mailto:vishalhirawat@proton.me"

[[params.social]]
name = "twitter"
icon = "twitter"
url = "https://twitter.com/hirawattt"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
tag = "tags"

[sitemap]
changefreq = 'monthly'
filename = 'sitemap.xml'
priority = 0.5